version: "3.3" 
services:
    mixnode:
      image: cgibin/nym-mixnode:1.0
      restart: unless-stopped
      ports:
        - "1789:1789"
        - "8000:8000"
        - "1790:1790"
      volumes:
        - ./nym-data:/home/user/.nym/mixnodes
